/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  docs: [
    // {
    //   type: "category",
    //   label: "Tutorial",
    //   items: ["greeting", "tutorial-basics"],
    // },
    'intro',
    {
      type: 'category',
      label: '工具',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Git',
          link: {
            type: 'generated-index',
            description: "Let's learn Git!",
            keywords: ['git']
          },
          collapsed: false,
          items: ['tools/git/gitmoji']
        },
        {
          type: 'category',
          label: 'Lerna',
          link: {
            type: 'generated-index',
            description: "Let's learn Lerna!",
            keywords: ['Lerna']
          },
          collapsed: false,
          items: ['tools/lerna/learn-lerna']
        },
        {
          type: 'category',
          label: 'NPM',
          link: {
            type: 'generated-index',
            description: "Let's learn NPM!",
            keywords: ['NPM']
          },
          collapsed: false,
          items: ['tools/npm/learn-npm']
        }
      ]
    },
    {
      type: 'category',
      label: '前端',
      collapsed: false,
      items: [
        'web/react/custom-templates',

        {
          type: 'category',
          label: 'React',
          link: {
            type: 'generated-index',
            description: "Let's learn React!",
            keywords: ['react']
          },
          collapsed: false,
          items: ['web/react/cra-advanced-config', 'web/react/learn-react']
        }
        // {
        //   type: 'category',
        //   label: 'Vue',
        //   link: {
        //     type: 'generated-index',
        //     description: "Let's learn Vue!",
        //     keywords: ['vue']
        //   },
        //   collapsed: false,
        //   items: ['web/vue/learn-vue']
        // }
      ]
    }
  ]
};

module.exports = sidebars;
