/*
 * @Author: Roy
 * @Date: 2022-03-17 21:06:55
 * @LastEditors: Roy
 * @LastEditTime: 2022-09-28 16:52:10
 * @Description: 文档菜单
 */
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
const tools = require("./sidebars/tools");

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
    // But you can create a sidebar manually
    docs: [
        "intro",
        {
            type: "category",
            label: "Solana",
            items: [
                {
                    type: "category",
                    label: "安装Solana环境",
                    link: {
                        type: "generated-index",
                        description: "A Starter Kit for New Solana Developer",
                        keywords: ["Solana"],
                    },
                    items: ["solana/install-solana-env"],
                },
                {
                    type: "category",
                    label: "SPL Token",
                    link: {
                        type: "generated-index",
                        description: "SPL Token Program",
                        keywords: ["Solana"],
                    },
                    items: ["solana/token-program"],
                },
                {
                    type: "category",
                    label: "Solana中文开发教程",
                    link: {
                        type: "generated-index",
                        description: "Solana中文开发教程",
                        keywords: ["Solana"],
                    },
                    items: [
                        {
                            type: "category",
                            label: "1、Solana基础知识",
                            link: {
                                type: "generated-index",
                                description: "Solana中文开发教程",
                                keywords: ["Solana"],
                            },
                            items: [
                                "solana/solana-bootcamp/1、Solana基础知识/solana-intro",
                                "solana/solana-bootcamp/1、Solana基础知识/solana-core",
                                "solana/solana-bootcamp/1、Solana基础知识/solana-spl",
                                "solana/solana-bootcamp/1、Solana基础知识/solana-cmd",
                                "solana/solana-bootcamp/1、Solana基础知识/solana-wallet",
                                "solana/solana-bootcamp/1、Solana基础知识/solana-exercise6",
                            ],
                        },
                        {
                            type: "category",
                            label: "2、通过与RPC交互",
                            link: {
                                type: "generated-index",
                                description: "Solana中文开发教程",
                                keywords: ["Solana"],
                            },
                            items: [
                                "solana/solana-bootcamp/2、通过RPC与Solana交互/solana-rpc-intro",
                                "solana/solana-bootcamp/2、通过RPC与Solana交互/solana-interface-rpc",
                                "solana/solana-bootcamp/2、通过RPC与Solana交互/solana-push-rpc",
                                "solana/solana-bootcamp/2、通过RPC与Solana交互/solana-rpc-exercise",
                            ],
                        },
                        {
                            type: "category",
                            label: "3、与Solana合约交互",
                            link: {
                                type: "generated-index",
                                description: "Solana中文开发教程",
                                keywords: ["Solana"],
                            },
                            items: [
                                "solana/solana-bootcamp/3、与Solana合约交互/solana-web3.js",
                                "solana/solana-bootcamp/3、与Solana合约交互/solana-wallet-interactive",
                                "solana/solana-bootcamp/3、与Solana合约交互/solana-contract-call",
                                "solana/solana-bootcamp/3、与Solana合约交互/solana-contract-execise",
                            ],
                        },
                    ],
                },
            ],
        },
        {
            type: "category",
            label: "前端",
            items: [
                "web/react/custom-templates",

                {
                    type: "category",
                    label: "React",
                    link: {
                        type: "generated-index",
                        description: "Let's learn React!",
                        keywords: ["react"],
                    },
                    items: [
                        "web/react/cra-advanced-config",
                        "web/react/learn-react",
                    ],
                },
            ],
        },
    ],
    tools,
};

module.exports = sidebars;
